name: uippl-sandbox
recipe: drupal8
config:
  webroot: web
services:
  appserver:
    xdebug: true
  database:
    type: mysql:5.7
tooling:
  behat:
    service: appserver
    description: Run behat tests locally.
    cmd:
      - /app/vendor/bin/behat